// This file is auto-generated by @hey-api/openapi-ts

export const AgentCacheStatsSchema = {
    type: 'object',
    required: [
        'len',
        'capacity'
    ],
    properties: {
        len: {
            type: 'integer',
            description: 'Number of results currently buffered in the local cache',
            example: 42
        },
        capacity: {
            type: 'integer',
            description: 'Maximum number of results the cache can hold (hard cap)',
            example: 10000
        }
    }
} as const;

export const AgentConfigSchema = {
    type: 'object',
    required: [
        'version',
        'agent_id',
        'agent_name',
        'monitoring',
        'server',
        'storage',
        'endpoints'
    ],
    properties: {
        version: {
            type: 'integer',
            format: 'int32',
            description: 'Configuration version (used for syncing with server)',
            example: 1
        },
        agent_id: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'Unique identifier for this agent',
            example: '0197f96c-b278-7f64-a32f-dae3cabe1ff0'
        },
        agent_name: {
            type: 'string',
            description: 'Human-readable agent name',
            example: 'Production Server 1'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            },
            description: 'Tags for this agent (used for mesh organization)',
            example: [
                'production',
                'web-server',
                'us-east'
            ]
        },
        monitoring: {
            $ref: '#/components/schemas/MonitoringConfig'
        },
        server: {
            $ref: '#/components/schemas/ServerConfig'
        },
        storage: {
            $ref: '#/components/schemas/StorageConfig'
        },
        endpoints: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Endpoint'
            },
            description: 'Endpoints to monitor'
        }
    }
} as const;

export const MonitoringConfigSchema = {
    type: 'object',
    required: [
        'interval_secs',
        'timeout_secs',
        'ping_count',
        'max_concurrent',
        'traceroute_on_failure',
        'traceroute_max_hops'
    ],
    properties: {
        interval_secs: {
            type: 'integer',
            format: 'int64',
            description: 'Interval between checks in seconds',
            default: 60,
            minimum: 1,
            example: 60
        },
        timeout_secs: {
            type: 'integer',
            format: 'int64',
            description: 'Timeout for each check in seconds',
            default: 1,
            minimum: 1,
            example: 5
        },
        ping_count: {
            type: 'integer',
            format: 'int32',
            description: 'Number of pings to send per check',
            default: 3,
            minimum: 1,
            maximum: 100,
            example: 3
        },
        max_concurrent: {
            type: 'integer',
            description: 'Maximum number of concurrent checks',
            default: 10,
            minimum: 1,
            example: 10
        },
        traceroute_on_failure: {
            type: 'boolean',
            description: 'Enable traceroute on failed pings',
            default: false,
            example: false
        },
        traceroute_max_hops: {
            type: 'integer',
            format: 'int32',
            description: 'Maximum TTL for traceroute',
            default: 30,
            minimum: 1,
            maximum: 255,
            example: 30
        }
    }
} as const;

export const ServerConfigSchema = {
    type: 'object',
    required: [
        'report_interval_secs',
        'heartbeat_interval_secs',
        'verify_tls',
        'timeout_secs',
        'retry_attempts'
    ],
    properties: {
        url: {
            type: 'string',
            format: 'uri',
            description: 'Server URL',
            nullable: true,
            example: 'https://api.smotra.net'
        },
        api_key: {
            type: 'string',
            description: 'API key for authentication',
            nullable: true,
            example: 'sk_live_1234567890abcdef'
        },
        report_interval_secs: {
            type: 'integer',
            format: 'int64',
            description: 'Report interval in seconds',
            default: 300,
            minimum: 1,
            example: 300
        },
        heartbeat_interval_secs: {
            type: 'integer',
            format: 'int64',
            description: 'Heartbeat interval in seconds',
            default: 300,
            minimum: 1,
            example: 300
        },
        verify_tls: {
            type: 'boolean',
            description: 'Enable TLS verification',
            default: true,
            example: true
        },
        timeout_secs: {
            type: 'integer',
            format: 'int64',
            description: 'Connection timeout in seconds',
            default: 5,
            minimum: 1,
            example: 5
        },
        retry_attempts: {
            type: 'integer',
            format: 'int32',
            description: 'Retry attempts on failure',
            default: 3,
            minimum: 0,
            example: 3
        }
    }
} as const;

export const StorageConfigSchema = {
    type: 'object',
    required: [
        'cache_dir',
        'max_cached_results',
        'max_cache_age_secs'
    ],
    properties: {
        cache_dir: {
            type: 'string',
            description: 'Directory for storing cached data',
            default: './cache',
            example: './cache'
        },
        max_cached_results: {
            type: 'integer',
            description: 'Maximum number of results to cache',
            default: 10000,
            minimum: 0,
            example: 10000
        },
        max_cache_age_secs: {
            type: 'integer',
            format: 'int64',
            description: 'Maximum age of cached results in seconds (e.g., 86400 = 24 hours)',
            default: 86400,
            minimum: 0,
            example: 86400
        }
    }
} as const;

export const EndpointSchema = {
    type: 'object',
    description: 'An endpoint to monitor (IP address, hostname, or URL)',
    required: [
        'id',
        'address',
        'enabled',
        'tags'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'Unique identifier for the monitoring target'
        },
        address: {
            type: 'string',
            description: 'IP address, hostname, or URL'
        },
        port: {
            type: 'integer',
            minimum: 1,
            maximum: 65535
        },
        enabled: {
            type: 'boolean',
            default: true
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            },
            description: 'Tags associated with the target',
            example: [
                'database',
                'critical'
            ]
        }
    }
} as const;

export const MonitoringResultSchema = {
    type: 'object',
    required: [
        'id',
        'agent_id',
        'endpoint_id',
        'check_type',
        'timestamp'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'Unique identifier for the monitoring result'
        },
        agent_id: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'Unique identifier for the agent'
        },
        endpoint_id: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'UUID of the endpoint being monitored'
        },
        check_type: {
            $ref: '#/components/schemas/CheckType',
            description: 'Type of check performed'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'Timestamp when the report was generated (RFC3339)',
            example: '2025-11-19T10:30:00Z'
        }
    }
} as const;

export const BatchMonitoringResultsSchema = {
    type: 'object',
    required: [
        'results'
    ],
    description: 'A batch of monitoring results submitted by an agent from its local cache.\nThe server deduplicates entries by `MonitoringResult.id`.\n',
    properties: {
        results: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MonitoringResult'
            },
            description: 'Ordered list of monitoring results (oldest-first)'
        }
    }
} as const;

export const CheckTypeSchema = {
    oneOf: [
        {
            $ref: '#/components/schemas/PingCheck'
        },
        {
            $ref: '#/components/schemas/TracerouteCheck'
        },
        {
            $ref: '#/components/schemas/TcpConnectCheck'
        },
        {
            $ref: '#/components/schemas/UdpConnectCheck'
        },
        {
            $ref: '#/components/schemas/HttpGetCheck'
        },
        {
            $ref: '#/components/schemas/PluginCheck'
        }
    ],
    discriminator: {
        propertyName: 'type',
        mapping: {
            ping: '#/components/schemas/PingCheck',
            traceroute: '#/components/schemas/TracerouteCheck',
            tcpconnect: '#/components/schemas/TcpConnectCheck',
            udpconnect: '#/components/schemas/UdpConnectCheck',
            httpget: '#/components/schemas/HttpGetCheck',
            plugin: '#/components/schemas/PluginCheck'
        }
    }
} as const;

export const PingCheckTypeSchema = {
    type: 'string',
    enum: [
        'ping'
    ]
} as const;

export const TracerouteCheckTypeSchema = {
    type: 'string',
    enum: [
        'traceroute'
    ]
} as const;

export const TcpConnectCheckTypeSchema = {
    type: 'string',
    enum: [
        'tcpconnect'
    ]
} as const;

export const UdpConnectCheckTypeSchema = {
    type: 'string',
    enum: [
        'udpconnect'
    ]
} as const;

export const HttpGetCheckTypeSchema = {
    type: 'string',
    enum: [
        'httpget'
    ]
} as const;

export const PluginCheckTypeSchema = {
    type: 'string',
    enum: [
        'plugin'
    ]
} as const;

export const PingCheckSchema = {
    type: 'object',
    required: [
        'type',
        'result'
    ],
    properties: {
        type: {
            $ref: '#/components/schemas/PingCheckType'
        },
        result: {
            $ref: '#/components/schemas/PingResult'
        }
    }
} as const;

export const PingResultSchema = {
    type: 'object',
    required: [
        'resolved_ip',
        'successes',
        'failures',
        'success_latencies'
    ],
    properties: {
        resolved_ip: {
            type: 'string',
            format: 'ipv4',
            description: 'Resolved IP address of the target',
            example: '4.2.2.2'
        },
        successes: {
            type: 'integer',
            format: 'int32'
        },
        failures: {
            type: 'integer',
            format: 'int32'
        },
        success_latencies: {
            type: 'array',
            items: {
                type: 'number',
                format: 'double'
            },
            example: [
                12.5,
                13,
                11.8
            ]
        },
        error_details: {
            $ref: '#/components/schemas/ErrorDetails',
            nullable: true
        }
    }
} as const;

export const TracerouteCheckSchema = {
    type: 'object',
    required: [
        'type',
        'result'
    ],
    properties: {
        type: {
            $ref: '#/components/schemas/TracerouteCheckType'
        },
        result: {
            $ref: '#/components/schemas/TracerouteResult'
        }
    }
} as const;

export const TracerouteResultSchema = {
    type: 'object',
    required: [
        'hops',
        'target_reached'
    ],
    properties: {
        hops: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TracerouteHop'
            }
        },
        target_reached: {
            type: 'boolean'
        },
        error_details: {
            $ref: '#/components/schemas/ErrorDetails',
            nullable: true
        }
    }
} as const;

export const TracerouteHopSchema = {
    type: 'object',
    required: [
        'hop'
    ],
    properties: {
        hop: {
            type: 'integer',
            format: 'int32'
        },
        resolved_ip: {
            type: 'string',
            format: 'ipv4',
            description: 'Resolved IP address of the target',
            example: '4.2.2.2'
        },
        success_latencies: {
            type: 'array',
            items: {
                type: 'number',
                format: 'double'
            },
            example: [
                12.5,
                13,
                11.8
            ]
        },
        hostname: {
            type: 'string'
        }
    }
} as const;

export const TcpConnectCheckSchema = {
    type: 'object',
    required: [
        'type',
        'result'
    ],
    properties: {
        type: {
            $ref: '#/components/schemas/TcpConnectCheckType'
        },
        result: {
            $ref: '#/components/schemas/TcpConnectResult'
        }
    }
} as const;

export const TcpConnectResultSchema = {
    type: 'object',
    required: [
        'connected',
        'resolved_ip'
    ],
    properties: {
        connected: {
            type: 'boolean'
        },
        connect_time_ms: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        error_details: {
            $ref: '#/components/schemas/ErrorDetails',
            nullable: true
        },
        resolved_ip: {
            type: 'string'
        }
    }
} as const;

export const UdpConnectCheckSchema = {
    type: 'object',
    required: [
        'type',
        'result'
    ],
    properties: {
        type: {
            $ref: '#/components/schemas/UdpConnectCheckType'
        },
        result: {
            $ref: '#/components/schemas/UdpConnectResult'
        }
    }
} as const;

export const UdpConnectResultSchema = {
    type: 'object',
    required: [
        'probe_successful',
        'resolved_ip'
    ],
    properties: {
        probe_successful: {
            type: 'boolean'
        },
        response_time_ms: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        error_details: {
            $ref: '#/components/schemas/ErrorDetails',
            nullable: true
        },
        resolved_ip: {
            type: 'string'
        }
    }
} as const;

export const HttpGetCheckSchema = {
    type: 'object',
    required: [
        'type',
        'result'
    ],
    properties: {
        type: {
            $ref: '#/components/schemas/HttpGetCheckType'
        },
        result: {
            $ref: '#/components/schemas/HttpGetResult'
        }
    }
} as const;

export const HttpGetResultSchema = {
    type: 'object',
    required: [
        'status_code',
        'success'
    ],
    properties: {
        status_code: {
            type: 'integer',
            format: 'int32'
        },
        response_time_ms: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        response_size_bytes: {
            type: 'integer',
            format: 'int64',
            nullable: true
        },
        error_details: {
            $ref: '#/components/schemas/ErrorDetails',
            nullable: true
        },
        success: {
            type: 'boolean'
        }
    }
} as const;

export const PluginCheckSchema = {
    type: 'object',
    required: [
        'type',
        'result'
    ],
    properties: {
        type: {
            $ref: '#/components/schemas/PluginCheckType'
        },
        result: {
            $ref: '#/components/schemas/PluginResult'
        }
    }
} as const;

export const PluginResultSchema = {
    type: 'object',
    required: [
        'plugin_name',
        'plugin_version',
        'success',
        'data'
    ],
    properties: {
        plugin_name: {
            type: 'string'
        },
        plugin_version: {
            type: 'string'
        },
        success: {
            type: 'boolean'
        },
        response_time_ms: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        error_details: {
            $ref: '#/components/schemas/ErrorDetails',
            nullable: true
        },
        data: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            }
        }
    }
} as const;

export const ErrorDetailsSchema = {
    type: 'object',
    nullable: true,
    description: 'Error information from a check, stored as an extensible JSON object',
    properties: {
        errors: {
            type: 'array',
            items: {
                type: 'string'
            },
            description: 'List of error messages from the check',
            example: [
                'Timeout',
                'Host unreachable'
            ]
        }
    }
} as const;

export const AgentHeartbeatSchema = {
    type: 'object',
    required: [
        'timestamp',
        'status',
        'cpu_usage_percent',
        'memory_usage_mb',
        'memory_total_mb',
        'system_uptime_secs'
    ],
    properties: {
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'Agent-local timestamp when the heartbeat was generated (RFC3339)'
        },
        status: {
            $ref: '#/components/schemas/AgentHealthStatus',
            description: 'Health status of the agent'
        },
        cpu_usage_percent: {
            type: 'number',
            format: 'float',
            minimum: 0,
            maximum: 100,
            description: 'CPU utilization percentage (0.0–100.0)'
        },
        memory_usage_mb: {
            type: 'number',
            format: 'float',
            minimum: 0,
            description: 'Resident memory currently in use (MB)'
        },
        memory_total_mb: {
            type: 'number',
            format: 'float',
            minimum: 0,
            description: 'Total physical memory available (MB)'
        },
        system_uptime_secs: {
            type: 'integer',
            format: 'int64',
            minimum: 0,
            description: 'System uptime in seconds'
        }
    }
} as const;

export const MetricSchema = {
    type: 'object',
    required: [
        'type',
        'target',
        'status'
    ],
    properties: {
        type: {
            type: 'string',
            enum: [
                'icmp_ping',
                'tcp_check',
                'http_check',
                'traceroute',
                'custom'
            ],
            description: 'Type of check performed'
        },
        target: {
            type: 'string',
            description: 'Target host, IP, or URL',
            example: '192.168.1.100'
        },
        status: {
            $ref: '#/components/schemas/MetricStatus',
            description: 'Status of the check'
        },
        response_time_ms: {
            type: 'number',
            format: 'float',
            nullable: true,
            description: 'Response time in milliseconds',
            example: 12.5
        },
        packet_loss_percent: {
            type: 'number',
            format: 'float',
            minimum: 0,
            maximum: 100,
            nullable: true,
            description: 'Packet loss percentage for ping checks'
        },
        status_code: {
            type: 'integer',
            nullable: true,
            description: 'HTTP status code for HTTP checks'
        },
        error_message: {
            type: 'string',
            nullable: true,
            description: 'Error message if check failed'
        },
        metadata: {
            type: 'object',
            additionalProperties: true,
            description: 'Additional metric-specific data'
        }
    }
} as const;

export const AgentRegistrationSchema = {
    type: 'object',
    required: [
        'hostname',
        'ip_address'
    ],
    properties: {
        hostname: {
            type: 'string',
            example: 'web-server-01'
        },
        ip_address: {
            type: 'string',
            format: 'ipv4',
            example: '192.168.1.100'
        },
        agent_version: {
            type: 'string',
            example: '1.2.3'
        },
        os: {
            type: 'string',
            example: 'linux'
        },
        arch: {
            type: 'string',
            example: 'x86_64'
        },
        tags: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            },
            description: 'Custom tags for organizing agents',
            example: {
                environment: 'production',
                datacenter: 'us-east-1'
            }
        }
    }
} as const;

export const AgentNetworkInterfaceSchema = {
    type: 'object',
    required: [
        'ip',
        'iface',
        'family',
        'recommended'
    ],
    properties: {
        ip: {
            type: 'string',
            description: 'IP address of the network interface (IPv4 or IPv6, excluding loopback and link-local)',
            example: '192.168.1.10'
        },
        iface: {
            type: 'string',
            description: 'Name of the network interface',
            example: 'eth0'
        },
        family: {
            $ref: '#/components/schemas/IpAddressFamily',
            description: 'IP address family',
            example: 'ipv4'
        },
        recommended: {
            type: 'boolean',
            description: 'Whether this address is recommended for the server to use when communicating\nwith the agent. Determined by the agent using the OS routing table: the source\nIP the OS selects when opening a connection toward the server is marked as\nrecommended. Only one entry will have recommended=true.\n',
            example: true
        }
    }
} as const;

export const AgentSchema = {
    type: 'object',
    required: [
        'id',
        'sectionId',
        'name',
        'configVersion',
        'createdAt',
        'updatedAt'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'Unique agent identifier'
        },
        sectionId: {
            type: 'string',
            description: 'Section (organizational unit) this agent belongs to',
            example: '01930000-0000-7000-0000-000000000001'
        },
        name: {
            type: 'string',
            description: 'Human-readable agent name',
            example: 'prod-server-01'
        },
        configVersion: {
            type: 'integer',
            description: 'Current configuration version',
            example: 3
        },
        agentVersion: {
            type: 'string',
            nullable: true,
            description: 'Version of the agent software, null if not yet reported',
            example: '1.2.0'
        },
        ipAddresses: {
            type: 'array',
            description: 'Network interfaces reported by the agent',
            items: {
                $ref: '#/components/schemas/AgentNetworkInterface'
            }
        },
        lastSeenAt: {
            type: 'string',
            format: 'date-time',
            nullable: true,
            description: 'Timestamp of the last heartbeat received from the agent',
            example: '2026-05-30T10:00:00Z'
        },
        lastResultSubmittedAt: {
            type: 'string',
            format: 'date-time',
            nullable: true,
            description: 'Timestamp of the last monitoring result submission',
            example: '2026-05-30T09:55:00Z'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            description: 'Timestamp when the agent was registered',
            example: '2026-01-01T00:00:00Z'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            description: 'Timestamp when the agent record was last updated',
            example: '2026-05-30T10:00:00Z'
        }
    }
} as const;

export const AgentListResponseSchema = {
    type: 'object',
    required: [
        'agents',
        'pagination'
    ],
    properties: {
        agents: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Agent'
            }
        },
        pagination: {
            $ref: '#/components/schemas/Pagination'
        }
    }
} as const;

export const AgentSelfRegistrationSchema = {
    type: 'object',
    required: [
        'agentId',
        'claimTokenHash',
        'hostname',
        'agentVersion',
        'ipAddresses'
    ],
    properties: {
        agentId: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'Self-generated UUIDv7 identifier for this agent',
            example: '0197f96c-b278-7f64-a32f-dae3cabe1ff0'
        },
        claimTokenHash: {
            type: 'string',
            minLength: 64,
            maxLength: 64,
            pattern: '^[a-f0-9]{64}$',
            description: 'SHA-256 hash of the claim token (plain token shown in agent logs for user)',
            example: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8'
        },
        hostname: {
            type: 'string',
            description: 'System hostname of the machine running the agent',
            example: 'prod-server-01'
        },
        agentVersion: {
            type: 'string',
            description: 'Version of the agent software',
            example: '1.0.0'
        },
        ipAddresses: {
            type: 'array',
            description: 'List of all non-loopback, non-link-local network interfaces on the agent host.\nLoopback (127.x.x.x / ::1) and link-local (169.254.x.x / fe80::/10) addresses\nare excluded. The server should store all addresses and allow the operator to\nselect the preferred one during the claim process. The entry with\nrecommended=true reflects the OS-selected source IP for connections toward\nthe server (determined via routing table, no traffic sent).\n',
            minItems: 1,
            items: {
                $ref: '#/components/schemas/AgentNetworkInterface'
            },
            example: [
                {
                    ip: '192.168.1.10',
                    iface: 'eth0',
                    family: 'ipv4',
                    recommended: true
                },
                {
                    ip: '10.0.0.5',
                    iface: 'eth1',
                    family: 'ipv4',
                    recommended: false
                },
                {
                    ip: '2001:db8::1',
                    iface: 'eth0',
                    family: 'ipv6',
                    recommended: false
                }
            ]
        }
    }
} as const;

export const AgentRegistrationResponseSchema = {
    type: 'object',
    required: [
        'status',
        'pollUrl',
        'claimUrl',
        'expiresAt'
    ],
    properties: {
        status: {
            title: 'RegistrationStatus',
            $ref: '#/components/schemas/RegistrationStatus',
            description: 'Current status of the registration'
        },
        pollUrl: {
            type: 'string',
            format: 'uri-reference',
            description: 'URL for agent to poll for claim status',
            example: '/agent/0197f96c-b278-7f64-a32f-dae3cabe1ff0/claim-status'
        },
        claimUrl: {
            type: 'string',
            format: 'uri',
            description: 'URL for user to claim the agent (web UI)',
            example: 'https://yoursite.com/claim'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time',
            description: 'When the claim token expires (RFC3339)',
            example: '2026-02-01T12:00:00Z'
        }
    }
} as const;

export const ClaimStatusPendingSchema = {
    type: 'object',
    required: [
        'status',
        'expiresAt',
        'pollIn'
    ],
    properties: {
        status: {
            title: 'ClaimStatusPendingEnum',
            $ref: '#/components/schemas/ClaimStatusPendingEnum',
            description: 'Agent is waiting to be claimed'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time',
            description: 'When the claim token expires (RFC3339)',
            example: '2026-02-01T12:00:00Z'
        },
        pollIn: {
            type: 'integer',
            format: 'int32',
            description: 'Seconds until next poll (server-controlled backoff)',
            example: 30,
            minimum: 1
        }
    }
} as const;

export const ClaimStatusClaimedSchema = {
    type: 'object',
    required: [
        'status',
        'apiKey',
        'configUrl'
    ],
    properties: {
        status: {
            $ref: '#/components/schemas/ClaimStatusClaimedEnum',
            description: 'Agent has been claimed and API key is ready'
        },
        apiKey: {
            type: 'string',
            description: 'API key for authenticated requests (one-time delivery)'
        },
        configUrl: {
            type: 'string',
            format: 'uri-reference',
            description: 'URL to fetch agent configuration',
            example: '/agent/0197f96c-b278-7f64-a32f-dae3cabe1ff0/configuration'
        }
    }
} as const;

export const ClaimAgentRequestSchema = {
    type: 'object',
    required: [
        'agentId',
        'claimToken',
        'sectionId'
    ],
    properties: {
        agentId: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'Agent ID from agent logs',
            example: '0197f96c-b278-7f64-a32f-dae3cabe1ff0'
        },
        claimToken: {
            type: 'string',
            description: 'Claim token from agent logs',
            example: 'ABC123XY'
        },
        sectionId: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'Section to assign this agent to within your tenant',
            example: '0197f96d-1234-7f64-a32f-dae3cabe1ff0'
        },
        name: {
            type: 'string',
            description: 'Human-readable name for the agent (defaults to hostname if not provided)',
            example: 'Production Server 01'
        }
    }
} as const;

export const ClaimAgentResponseSchema = {
    type: 'object',
    required: [
        'agentId',
        'status',
        'message'
    ],
    properties: {
        agentId: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'The claimed agent\'s ID',
            example: '0197f96c-b278-7f64-a32f-dae3cabe1ff0'
        },
        status: {
            $ref: '#/components/schemas/ClaimResponseStatus',
            description: 'Claim status'
        },
        message: {
            type: 'string',
            description: 'Human-readable message',
            example: 'Agent will receive API key on next poll'
        }
    }
} as const;

export const PluginConfigurationSchema = {
    type: 'object',
    required: [
        'name',
        'enabled'
    ],
    properties: {
        name: {
            type: 'string'
        },
        version: {
            type: 'string'
        },
        enabled: {
            type: 'boolean'
        },
        configuration: {
            type: 'object',
            additionalProperties: true
        }
    }
} as const;

export const ThresholdsSchema = {
    type: 'object',
    properties: {
        response_time_warning_ms: {
            type: 'number',
            format: 'float',
            default: 100
        },
        response_time_critical_ms: {
            type: 'number',
            format: 'float',
            default: 500
        },
        packet_loss_warning_percent: {
            type: 'number',
            format: 'float',
            default: 10
        },
        packet_loss_critical_percent: {
            type: 'number',
            format: 'float',
            default: 50
        }
    }
} as const;

export const RetryPolicySchema = {
    type: 'object',
    properties: {
        max_retries: {
            type: 'integer',
            minimum: 0,
            default: 3
        },
        retry_delay_seconds: {
            type: 'integer',
            minimum: 1,
            default: 5
        },
        backoff_multiplier: {
            type: 'number',
            format: 'float',
            minimum: 1,
            default: 2
        }
    }
} as const;

export const ResultsBatchAcknowledgmentSchema = {
    type: 'object',
    required: [
        'submission_id',
        'accepted',
        'received_at'
    ],
    properties: {
        submission_id: {
            $ref: '#/components/schemas/UUIDv7',
            description: 'Server-assigned ID for this batch submission'
        },
        accepted: {
            type: 'integer',
            description: 'Number of results accepted for processing',
            example: 25
        },
        duplicates_skipped: {
            type: 'integer',
            description: 'Number of results deduplicated (already known to the server)',
            example: 0
        },
        received_at: {
            type: 'string',
            format: 'date-time',
            description: 'Timestamp when the batch was received by the server'
        }
    }
} as const;

export const ResultReportSchema = {
    type: 'object',
    required: [
        'time_range',
        'data',
        'pagination'
    ],
    properties: {
        time_range: {
            type: 'object',
            required: [
                'start',
                'end'
            ],
            properties: {
                start: {
                    type: 'string',
                    format: 'date-time'
                },
                end: {
                    type: 'string',
                    format: 'date-time'
                }
            }
        },
        aggregation: {
            type: 'string',
            example: '5m'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/AggregatedMetric'
            }
        },
        pagination: {
            $ref: '#/components/schemas/Pagination'
        },
        metadata: {
            type: 'object',
            properties: {
                total_checks: {
                    type: 'integer'
                },
                successful_checks: {
                    type: 'integer'
                },
                failed_checks: {
                    type: 'integer'
                },
                average_response_time_ms: {
                    type: 'number',
                    format: 'float'
                }
            }
        }
    }
} as const;

export const AggregatedMetricSchema = {
    type: 'object',
    required: [
        'timestamp',
        'agent_id',
        'target',
        'metric_type'
    ],
    properties: {
        timestamp: {
            type: 'string',
            format: 'date-time'
        },
        agent_id: {
            $ref: '#/components/schemas/UUIDv7'
        },
        hostname: {
            type: 'string'
        },
        target: {
            type: 'string'
        },
        metric_type: {
            type: 'string'
        },
        status: {
            $ref: '#/components/schemas/AggregatedMetricStatus'
        },
        avg_response_time_ms: {
            type: 'number',
            format: 'float'
        },
        min_response_time_ms: {
            type: 'number',
            format: 'float'
        },
        max_response_time_ms: {
            type: 'number',
            format: 'float'
        },
        p50_response_time_ms: {
            type: 'number',
            format: 'float'
        },
        p95_response_time_ms: {
            type: 'number',
            format: 'float'
        },
        p99_response_time_ms: {
            type: 'number',
            format: 'float'
        },
        success_rate_percent: {
            type: 'number',
            format: 'float'
        },
        check_count: {
            type: 'integer'
        }
    }
} as const;

export const MetricsResponseSchema = {
    type: 'object',
    required: [
        'metrics',
        'pagination'
    ],
    properties: {
        metrics: {
            type: 'array',
            items: {
                type: 'object',
                required: [
                    'timestamp',
                    'metric'
                ],
                properties: {
                    timestamp: {
                        type: 'string',
                        format: 'date-time'
                    },
                    metric: {
                        $ref: '#/components/schemas/Metric'
                    }
                }
            }
        },
        pagination: {
            $ref: '#/components/schemas/Pagination'
        }
    }
} as const;

export const SummaryStatisticsSchema = {
    type: 'object',
    properties: {
        time_range: {
            type: 'string',
            example: '24h'
        },
        total_agents: {
            type: 'integer'
        },
        active_agents: {
            type: 'integer'
        },
        inactive_agents: {
            type: 'integer'
        },
        total_targets: {
            type: 'integer'
        },
        reachable_targets: {
            type: 'integer'
        },
        unreachable_targets: {
            type: 'integer'
        },
        degraded_targets: {
            type: 'integer'
        },
        total_checks: {
            type: 'integer'
        },
        successful_checks: {
            type: 'integer'
        },
        failed_checks: {
            type: 'integer'
        },
        average_response_time_ms: {
            type: 'number',
            format: 'float'
        },
        active_alerts: {
            type: 'integer'
        },
        by_agent: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    agent_id: {
                        $ref: '#/components/schemas/UUIDv7'
                    },
                    hostname: {
                        type: 'string'
                    },
                    status: {
                        type: 'string'
                    },
                    checks_performed: {
                        type: 'integer'
                    },
                    success_rate_percent: {
                        type: 'number',
                        format: 'float'
                    }
                }
            }
        }
    }
} as const;

export const AlertSchema = {
    type: 'object',
    required: [
        'id',
        'rule_id',
        'status',
        'severity',
        'created_at'
    ],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        rule_id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        status: {
            $ref: '#/components/schemas/AlertStatus'
        },
        severity: {
            type: 'string',
            enum: [
                'critical',
                'warning',
                'info'
            ]
        },
        agent_id: {
            type: 'string'
        },
        target: {
            type: 'string'
        },
        metric_type: {
            type: 'string'
        },
        threshold_value: {
            type: 'number'
        },
        current_value: {
            type: 'number'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        acknowledged_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        acknowledged_by: {
            type: 'string',
            nullable: true
        },
        resolved_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        }
    }
} as const;

export const AlertRuleSchema = {
    type: 'object',
    required: [
        'name',
        'condition',
        'severity',
        'notifications'
    ],
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        name: {
            type: 'string',
            example: 'High Response Time Alert'
        },
        description: {
            type: 'string'
        },
        enabled: {
            type: 'boolean',
            default: true
        },
        condition: {
            $ref: '#/components/schemas/AlertCondition'
        },
        severity: {
            type: 'string',
            enum: [
                'critical',
                'warning',
                'info'
            ]
        },
        notifications: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/NotificationChannel'
            }
        },
        cooldown_seconds: {
            type: 'integer',
            minimum: 0,
            default: 300,
            description: 'Minimum time between repeat notifications'
        }
    }
} as const;

export const AlertConditionSchema = {
    type: 'object',
    required: [
        'metric',
        'operator',
        'threshold'
    ],
    properties: {
        metric: {
            type: 'string',
            enum: [
                'response_time_ms',
                'packet_loss_percent',
                'status',
                'uptime_percent'
            ]
        },
        operator: {
            type: 'string',
            enum: [
                'greater_than',
                'less_than',
                'equals',
                'not_equals'
            ]
        },
        threshold: {
            type: 'number'
        },
        duration_seconds: {
            type: 'integer',
            minimum: 0,
            description: 'Condition must be true for this duration before alerting'
        },
        aggregation: {
            type: 'string',
            enum: [
                'avg',
                'min',
                'max',
                'sum',
                'count'
            ],
            default: 'avg'
        },
        filters: {
            type: 'object',
            properties: {
                agent_ids: {
                    type: 'array',
                    items: {
                        type: 'string'
                    }
                },
                targets: {
                    type: 'array',
                    items: {
                        type: 'string'
                    }
                },
                metric_types: {
                    type: 'array',
                    items: {
                        type: 'string'
                    }
                }
            }
        }
    }
} as const;

export const NotificationChannelSchema = {
    type: 'object',
    required: [
        'type'
    ],
    properties: {
        type: {
            type: 'string',
            enum: [
                'discord',
                'email',
                'webhook',
                'slack',
                'pagerduty',
                'teams'
            ]
        },
        configuration: {
            type: 'object',
            additionalProperties: true,
            description: 'Channel-specific configuration',
            examples: [
                {
                    type: 'discord',
                    configuration: {
                        webhook_url: 'https://discord.com/api/webhooks/...'
                    }
                },
                {
                    type: 'email',
                    configuration: {
                        recipients: [
                            'ops@example.com'
                        ],
                        subject_template: '[{{ severity }}] {{ title }}'
                    }
                },
                {
                    type: 'slack',
                    configuration: {
                        channel: '#alerts',
                        webhook_url: 'https://hooks.slack.com/services/...'
                    }
                }
            ]
        }
    }
} as const;

export const TokenResponseSchema = {
    type: 'object',
    required: [
        'opaque_token',
        'expires_at'
    ],
    properties: {
        opaque_token: {
            type: 'string',
            description: 'Server-managed opaque session token. Use as a Bearer token in the\nAuthorization header for all subsequent requests.\nFormat: st_live_<hex> (production) or st_test_<hex> (dev/test).\n',
            example: 'st_live_..............................'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            description: 'Hard expiry time (ISO 8601). The session will never be valid after\nthis timestamp regardless of activity. Use this to schedule a\nproactive re-login in the client (e.g. at the midpoint).\n',
            example: '2025-10-15T12:00:00Z'
        }
    }
} as const;

export const UserInfoSchema = {
    type: 'object',
    required: [
        'sub'
    ],
    properties: {
        sub: {
            type: 'string',
            description: 'Subject identifier (user ID)',
            example: 'user-12345'
        },
        email: {
            type: 'string',
            format: 'email',
            example: 'user@example.com'
        },
        email_verified: {
            type: 'boolean'
        },
        name: {
            type: 'string',
            example: 'John Doe'
        },
        given_name: {
            type: 'string',
            example: 'John'
        },
        family_name: {
            type: 'string',
            example: 'Doe'
        },
        picture: {
            type: 'string',
            format: 'uri',
            example: 'https://example.com/avatar.jpg'
        },
        organization_id: {
            type: 'string',
            format: 'uuid'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string'
            },
            example: [
                'admin',
                'operator'
            ]
        },
        permissions: {
            type: 'array',
            items: {
                type: 'string'
            },
            example: [
                'metrics:read',
                'agent:write'
            ]
        }
    }
} as const;

export const UserSchema = {
    type: 'object',
    required: [
        'id',
        'email',
        'created_at'
    ],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        name: {
            type: 'string'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'admin',
                    'operator',
                    'viewer'
                ]
            }
        },
        organization_id: {
            type: 'string',
            format: 'uuid'
        },
        status: {
            title: 'UserStatus',
            $ref: '#/components/schemas/UserStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        updated_at: {
            type: 'string',
            format: 'date-time'
        },
        last_login_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        identity_provider: {
            type: 'string',
            description: 'Which OAuth2 provider the user authenticated with',
            example: 'okta'
        },
        external_id: {
            type: 'string',
            description: 'User ID from external identity provider'
        }
    }
} as const;

export const CreateUserRequestSchema = {
    type: 'object',
    required: [
        'email',
        'roles'
    ],
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        name: {
            type: 'string'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'admin',
                    'operator',
                    'viewer'
                ]
            },
            minItems: 1
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            description: 'Required for super admins creating users in other orgs'
        }
    }
} as const;

export const UpdateUserRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        status: {
            $ref: '#/components/schemas/UpdateUserStatus'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'admin',
                    'operator',
                    'viewer'
                ]
            }
        }
    }
} as const;

export const OrganizationSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'created_at'
    ],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string',
            example: 'Acme Corporation'
        },
        slug: {
            type: 'string',
            pattern: '^[a-z0-9-]+$',
            example: 'acme-corp'
        },
        status: {
            $ref: '#/components/schemas/OrganizationStatus'
        },
        plan: {
            type: 'string',
            enum: [
                'free',
                'professional',
                'enterprise'
            ]
        },
        settings: {
            type: 'object',
            properties: {
                max_agents: {
                    type: 'integer'
                },
                retention_days: {
                    type: 'integer'
                },
                features: {
                    type: 'array',
                    items: {
                        type: 'string'
                    }
                }
            }
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        updated_at: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const CreateOrganizationRequestSchema = {
    type: 'object',
    required: [
        'name'
    ],
    properties: {
        name: {
            type: 'string'
        },
        slug: {
            type: 'string',
            pattern: '^[a-z0-9-]+$'
        },
        plan: {
            type: 'string',
            enum: [
                'free',
                'professional',
                'enterprise'
            ],
            default: 'free'
        }
    }
} as const;

export const SystemStatusSchema = {
    type: 'object',
    required: [
        'status',
        'timestamp'
    ],
    properties: {
        status: {
            title: 'SystemHealthStatus',
            $ref: '#/components/schemas/SystemHealthStatus'
        },
        timestamp: {
            type: 'string',
            format: 'date-time'
        },
        version: {
            type: 'string',
            example: '1.0.0'
        },
        uptime_seconds: {
            type: 'integer'
        },
        components: {
            $ref: '#/components/schemas/ComponentsStatus'
        }
    }
} as const;

export const ComponentsStatusSchema = {
    type: 'object',
    additionalProperties: {
        $ref: '#/components/schemas/ComponentStatus'
    },
    example: {
        database: {
            status: 'healthy',
            response_time_ms: 2.5
        },
        redis: {
            status: 'healthy',
            response_time_ms: 0.8
        },
        oauth_provider: {
            status: 'healthy',
            message: 'Connected to Okta'
        },
        agents: {
            status: 'healthy',
            message: '42 agents connected'
        },
        websocket: {
            status: 'healthy',
            message: '15 active connections'
        }
    }
} as const;

export const ComponentStatusSchema = {
    type: 'object',
    required: [
        'status'
    ],
    properties: {
        status: {
            title: 'ComponentHealthStatus',
            $ref: '#/components/schemas/ComponentHealthStatus'
        },
        message: {
            type: 'string'
        },
        response_time_ms: {
            type: 'number',
            format: 'float'
        }
    },
    example: {
        database: {
            status: 'healthy',
            response_time_ms: 2.5
        }
    }
} as const;

export const AgentHealthStatusSchema = {
    type: 'string',
    enum: [
        'healthy',
        'degraded'
    ],
    description: 'Health status of the agent'
} as const;

export const MetricStatusSchema = {
    type: 'string',
    enum: [
        'reachable',
        'unreachable',
        'degraded',
        'unknown'
    ],
    description: 'Status of a monitoring check'
} as const;

export const RegistrationStatusSchema = {
    type: 'string',
    enum: [
        'pending_claim'
    ],
    description: 'Status of agent registration'
} as const;

export const IpAddressFamilySchema = {
    type: 'string',
    enum: [
        'ipv4',
        'ipv6'
    ],
    description: 'IP address family (IPv4 or IPv6)'
} as const;

export const ClaimStatusPendingEnumSchema = {
    type: 'string',
    enum: [
        'pending_claim'
    ],
    description: 'Pending claim status'
} as const;

export const ClaimStatusClaimedEnumSchema = {
    type: 'string',
    enum: [
        'claimed'
    ],
    description: 'Claimed status'
} as const;

export const ClaimResponseStatusSchema = {
    type: 'string',
    enum: [
        'claimed'
    ],
    description: 'Status in claim response'
} as const;

export const ReportAckStatusSchema = {
    type: 'string',
    enum: [
        'accepted',
        'queued'
    ],
    description: 'Report acknowledgment status'
} as const;

export const AggregatedMetricStatusSchema = {
    type: 'string',
    enum: [
        'reachable',
        'unreachable',
        'degraded',
        'unknown'
    ],
    description: 'Metric status'
} as const;

export const AlertStatusSchema = {
    type: 'string',
    enum: [
        'active',
        'acknowledged',
        'resolved'
    ],
    description: 'Alert status'
} as const;

export const UserStatusSchema = {
    type: 'string',
    enum: [
        'active',
        'inactive',
        'suspended'
    ],
    description: 'User account status'
} as const;

export const UpdateUserStatusSchema = {
    type: 'string',
    enum: [
        'active',
        'inactive',
        'suspended'
    ],
    description: 'Updated user status'
} as const;

export const OrganizationStatusSchema = {
    type: 'string',
    enum: [
        'active',
        'suspended',
        'trial'
    ],
    description: 'Organization status'
} as const;

export const SystemHealthStatusSchema = {
    type: 'string',
    enum: [
        'healthy',
        'degraded',
        'unhealthy'
    ],
    description: 'System health status'
} as const;

export const ComponentHealthStatusSchema = {
    type: 'string',
    enum: [
        'healthy',
        'degraded',
        'unhealthy'
    ],
    description: 'Component health status'
} as const;

export const UUIDv7Schema = {
    type: 'string',
    format: 'uuid',
    description: 'UUID version 7 as per RFC 4122',
    example: '0183f5e2-1dd2-7f8a-9abc-1234567890ab',
    'x-rust-type': 'Uuid',
    'x-go-type': 'uuid.UUID',
    'x-go-type-import': {
        name: 'uuid',
        path: 'github.com/google/uuid'
    }
} as const;

export const PaginationSchema = {
    type: 'object',
    required: [
        'page',
        'page_size',
        'total_items',
        'total_pages'
    ],
    properties: {
        page: {
            type: 'integer',
            minimum: 1
        },
        page_size: {
            type: 'integer',
            minimum: 1
        },
        total_items: {
            type: 'integer'
        },
        total_pages: {
            type: 'integer'
        },
        has_next: {
            type: 'boolean'
        },
        has_previous: {
            type: 'boolean'
        }
    }
} as const;

export const ErrorSchema = {
    type: 'object',
    required: [
        'error',
        'message'
    ],
    properties: {
        error: {
            type: 'string',
            example: 'validation_error'
        },
        message: {
            type: 'string',
            example: 'Invalid request parameters'
        },
        details: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    field: {
                        type: 'string'
                    },
                    issue: {
                        type: 'string'
                    }
                }
            }
        },
        request_id: {
            type: 'string',
            format: 'uuid'
        },
        documentation_url: {
            type: 'string',
            format: 'uri',
            description: 'Link to relevant documentation'
        }
    }
} as const;

export const AlertRuleWritableSchema = {
    type: 'object',
    required: [
        'name',
        'condition',
        'severity',
        'notifications'
    ],
    properties: {
        name: {
            type: 'string',
            example: 'High Response Time Alert'
        },
        description: {
            type: 'string'
        },
        enabled: {
            type: 'boolean',
            default: true
        },
        condition: {
            $ref: '#/components/schemas/AlertCondition'
        },
        severity: {
            type: 'string',
            enum: [
                'critical',
                'warning',
                'info'
            ]
        },
        notifications: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/NotificationChannel'
            }
        },
        cooldown_seconds: {
            type: 'integer',
            minimum: 0,
            default: 300,
            description: 'Minimum time between repeat notifications'
        }
    }
} as const;
