// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.smotra.net/v1' | 'https://staging-api.smotra.net/v1' | 'http://localhost:8080/v1' | (string & {});
};

export type AgentCacheStats = {
    /**
     * Number of results currently buffered in the local cache
     */
    len: number;
    /**
     * Maximum number of results the cache can hold (hard cap)
     */
    capacity: number;
};

export type AgentConfig = {
    /**
     * Configuration version (used for syncing with server)
     */
    version: number;
    agent_id: UuiDv7;
    /**
     * Human-readable agent name
     */
    agent_name: string;
    /**
     * Tags for this agent (used for mesh organization)
     */
    tags?: Array<string>;
    monitoring: MonitoringConfig;
    server: ServerConfig;
    storage: StorageConfig;
    /**
     * Endpoints to monitor
     */
    endpoints: Array<Endpoint>;
};

export type MonitoringConfig = {
    /**
     * Interval between checks in seconds
     */
    interval_secs: bigint;
    /**
     * Timeout for each check in seconds
     */
    timeout_secs: bigint;
    /**
     * Number of pings to send per check
     */
    ping_count: number;
    /**
     * Maximum number of concurrent checks
     */
    max_concurrent: number;
    /**
     * Enable traceroute on failed pings
     */
    traceroute_on_failure: boolean;
    /**
     * Maximum TTL for traceroute
     */
    traceroute_max_hops: number;
};

export type ServerConfig = {
    /**
     * Server URL
     */
    url?: string | null;
    /**
     * API key for authentication
     */
    api_key?: string | null;
    /**
     * Report interval in seconds
     */
    report_interval_secs: bigint;
    /**
     * Heartbeat interval in seconds
     */
    heartbeat_interval_secs: bigint;
    /**
     * Enable TLS verification
     */
    verify_tls: boolean;
    /**
     * Connection timeout in seconds
     */
    timeout_secs: bigint;
    /**
     * Retry attempts on failure
     */
    retry_attempts: number;
};

export type StorageConfig = {
    /**
     * Directory for storing cached data
     */
    cache_dir: string;
    /**
     * Maximum number of results to cache
     */
    max_cached_results: number;
    /**
     * Maximum age of cached results in seconds (e.g., 86400 = 24 hours)
     */
    max_cache_age_secs: bigint;
};

/**
 * An endpoint to monitor (IP address, hostname, or URL)
 */
export type Endpoint = {
    id: UuiDv7;
    /**
     * IP address, hostname, or URL
     */
    address: string;
    port?: number;
    enabled: boolean;
    /**
     * Tags associated with the target
     */
    tags: Array<string>;
};

export type MonitoringResult = {
    id: UuiDv7;
    agent_id: UuiDv7;
    endpoint_id: UuiDv7;
    check_type: CheckType;
    /**
     * Timestamp when the report was generated (RFC3339)
     */
    timestamp: Date;
};

/**
 * A batch of monitoring results submitted by an agent from its local cache.
 * The server deduplicates entries by `MonitoringResult.id`.
 *
 */
export type BatchMonitoringResults = {
    /**
     * Ordered list of monitoring results (oldest-first)
     */
    results: Array<MonitoringResult>;
};

export type CheckType = ({
    type: 'ping';
} & PingCheck) | ({
    type: 'traceroute';
} & TracerouteCheck) | ({
    type: 'tcpconnect';
} & TcpConnectCheck) | ({
    type: 'udpconnect';
} & UdpConnectCheck) | ({
    type: 'httpget';
} & HttpGetCheck) | ({
    type: 'plugin';
} & PluginCheck);

export const PingCheckType = { PING: 'ping' } as const;

export type PingCheckType = typeof PingCheckType[keyof typeof PingCheckType];

export const TracerouteCheckType = { TRACEROUTE: 'traceroute' } as const;

export type TracerouteCheckType = typeof TracerouteCheckType[keyof typeof TracerouteCheckType];

export const TcpConnectCheckType = { TCPCONNECT: 'tcpconnect' } as const;

export type TcpConnectCheckType = typeof TcpConnectCheckType[keyof typeof TcpConnectCheckType];

export const UdpConnectCheckType = { UDPCONNECT: 'udpconnect' } as const;

export type UdpConnectCheckType = typeof UdpConnectCheckType[keyof typeof UdpConnectCheckType];

export const HttpGetCheckType = { HTTPGET: 'httpget' } as const;

export type HttpGetCheckType = typeof HttpGetCheckType[keyof typeof HttpGetCheckType];

export const PluginCheckType = { PLUGIN: 'plugin' } as const;

export type PluginCheckType = typeof PluginCheckType[keyof typeof PluginCheckType];

export type PingCheck = {
    type: PingCheckType;
    result: PingResult;
};

export type PingResult = {
    /**
     * Resolved IP address of the target
     */
    resolved_ip: string;
    successes: number;
    failures: number;
    success_latencies: Array<number>;
    error_details?: ErrorDetails;
};

export type TracerouteCheck = {
    type: TracerouteCheckType;
    result: TracerouteResult;
};

export type TracerouteResult = {
    hops: Array<TracerouteHop>;
    target_reached: boolean;
    error_details?: ErrorDetails;
};

export type TracerouteHop = {
    hop: number;
    /**
     * Resolved IP address of the target
     */
    resolved_ip?: string;
    success_latencies?: Array<number>;
    hostname?: string;
};

export type TcpConnectCheck = {
    type: TcpConnectCheckType;
    result: TcpConnectResult;
};

export type TcpConnectResult = {
    connected: boolean;
    connect_time_ms?: number | null;
    error_details?: ErrorDetails;
    resolved_ip: string;
};

export type UdpConnectCheck = {
    type: UdpConnectCheckType;
    result: UdpConnectResult;
};

export type UdpConnectResult = {
    probe_successful: boolean;
    response_time_ms?: number | null;
    error_details?: ErrorDetails;
    resolved_ip: string;
};

export type HttpGetCheck = {
    type: HttpGetCheckType;
    result: HttpGetResult;
};

export type HttpGetResult = {
    status_code: number;
    response_time_ms?: number | null;
    response_size_bytes?: bigint | null;
    error_details?: ErrorDetails;
    success: boolean;
};

export type PluginCheck = {
    type: PluginCheckType;
    result: PluginResult;
};

export type PluginResult = {
    plugin_name: string;
    plugin_version: string;
    success: boolean;
    response_time_ms?: number | null;
    error_details?: ErrorDetails;
    data: {
        [key: string]: string;
    };
};

/**
 * Error information from a check, stored as an extensible JSON object
 */
export type ErrorDetails = {
    /**
     * List of error messages from the check
     */
    errors?: Array<string>;
} | null;

export type AgentHeartbeat = {
    /**
     * Agent-local timestamp when the heartbeat was generated (RFC3339)
     */
    timestamp: Date;
    status: AgentHealthStatus;
    /**
     * CPU utilization percentage (0.0–100.0)
     */
    cpu_usage_percent: number;
    /**
     * Resident memory currently in use (MB)
     */
    memory_usage_mb: number;
    /**
     * Total physical memory available (MB)
     */
    memory_total_mb: number;
    /**
     * System uptime in seconds
     */
    system_uptime_secs: bigint;
};

export type Metric = {
    /**
     * Type of check performed
     */
    type: 'icmp_ping' | 'tcp_check' | 'http_check' | 'traceroute' | 'custom';
    /**
     * Target host, IP, or URL
     */
    target: string;
    status: MetricStatus;
    /**
     * Response time in milliseconds
     */
    response_time_ms?: number | null;
    /**
     * Packet loss percentage for ping checks
     */
    packet_loss_percent?: number | null;
    /**
     * HTTP status code for HTTP checks
     */
    status_code?: number | null;
    /**
     * Error message if check failed
     */
    error_message?: string | null;
    /**
     * Additional metric-specific data
     */
    metadata?: {
        [key: string]: unknown;
    };
};

export type AgentRegistration = {
    hostname: string;
    ip_address: string;
    agent_version?: string;
    os?: string;
    arch?: string;
    /**
     * Custom tags for organizing agents
     */
    tags?: {
        [key: string]: string;
    };
};

export type AgentNetworkInterface = {
    /**
     * IP address of the network interface (IPv4 or IPv6, excluding loopback and link-local)
     */
    ip: string;
    /**
     * Name of the network interface
     */
    iface: string;
    family: IpAddressFamily;
    /**
     * Whether this address is recommended for the server to use when communicating
     * with the agent. Determined by the agent using the OS routing table: the source
     * IP the OS selects when opening a connection toward the server is marked as
     * recommended. Only one entry will have recommended=true.
     *
     */
    recommended: boolean;
};

export type Agent = {
    id: UuiDv7;
    /**
     * Section (organizational unit) this agent belongs to
     */
    sectionId: string;
    /**
     * Human-readable agent name
     */
    name: string;
    /**
     * Current configuration version
     */
    configVersion: number;
    /**
     * Version of the agent software, null if not yet reported
     */
    agentVersion?: string | null;
    /**
     * Network interfaces reported by the agent
     */
    ipAddresses?: Array<AgentNetworkInterface>;
    /**
     * Timestamp of the last heartbeat received from the agent
     */
    lastSeenAt?: Date | null;
    /**
     * Timestamp of the last monitoring result submission
     */
    lastResultSubmittedAt?: Date | null;
    /**
     * Timestamp when the agent was registered
     */
    createdAt: Date;
    /**
     * Timestamp when the agent record was last updated
     */
    updatedAt: Date;
};

export type AgentListResponse = {
    agents: Array<Agent>;
    pagination: Pagination;
};

export type AgentSelfRegistration = {
    agentId: UuiDv7;
    /**
     * SHA-256 hash of the claim token (plain token shown in agent logs for user)
     */
    claimTokenHash: string;
    /**
     * System hostname of the machine running the agent
     */
    hostname: string;
    /**
     * Version of the agent software
     */
    agentVersion: string;
    /**
     * List of all non-loopback, non-link-local network interfaces on the agent host.
     * Loopback (127.x.x.x / ::1) and link-local (169.254.x.x / fe80::/10) addresses
     * are excluded. The server should store all addresses and allow the operator to
     * select the preferred one during the claim process. The entry with
     * recommended=true reflects the OS-selected source IP for connections toward
     * the server (determined via routing table, no traffic sent).
     *
     */
    ipAddresses: Array<AgentNetworkInterface>;
};

export type AgentRegistrationResponse = {
    status: RegistrationStatus;
    /**
     * URL for agent to poll for claim status
     */
    pollUrl: string;
    /**
     * URL for user to claim the agent (web UI)
     */
    claimUrl: string;
    /**
     * When the claim token expires (RFC3339)
     */
    expiresAt: Date;
};

export type ClaimStatusPending = {
    status: ClaimStatusPendingEnum;
    /**
     * When the claim token expires (RFC3339)
     */
    expiresAt: Date;
    /**
     * Seconds until next poll (server-controlled backoff)
     */
    pollIn: number;
};

export type ClaimStatusClaimed = {
    status: ClaimStatusClaimedEnum;
    /**
     * API key for authenticated requests (one-time delivery)
     */
    apiKey: string;
    /**
     * URL to fetch agent configuration
     */
    configUrl: string;
};

export type ClaimAgentRequest = {
    agentId: UuiDv7;
    /**
     * Claim token from agent logs
     */
    claimToken: string;
    sectionId: UuiDv7;
    /**
     * Human-readable name for the agent (defaults to hostname if not provided)
     */
    name?: string;
};

export type ClaimAgentResponse = {
    agentId: UuiDv7;
    status: ClaimResponseStatus;
    /**
     * Human-readable message
     */
    message: string;
};

export type PluginConfiguration = {
    name: string;
    version?: string;
    enabled: boolean;
    configuration?: {
        [key: string]: unknown;
    };
};

export type Thresholds = {
    response_time_warning_ms?: number;
    response_time_critical_ms?: number;
    packet_loss_warning_percent?: number;
    packet_loss_critical_percent?: number;
};

export type RetryPolicy = {
    max_retries?: number;
    retry_delay_seconds?: number;
    backoff_multiplier?: number;
};

export type ResultsBatchAcknowledgment = {
    submission_id: UuiDv7;
    /**
     * Number of results accepted for processing
     */
    accepted: number;
    /**
     * Number of results deduplicated (already known to the server)
     */
    duplicates_skipped?: number;
    /**
     * Timestamp when the batch was received by the server
     */
    received_at: Date;
};

export type ResultReport = {
    time_range: {
        start: Date;
        end: Date;
    };
    aggregation?: string;
    data: Array<AggregatedMetric>;
    pagination: Pagination;
    metadata?: {
        total_checks?: number;
        successful_checks?: number;
        failed_checks?: number;
        average_response_time_ms?: number;
    };
};

export type AggregatedMetric = {
    timestamp: Date;
    agent_id: UuiDv7;
    hostname?: string;
    target: string;
    metric_type: string;
    status?: AggregatedMetricStatus;
    avg_response_time_ms?: number;
    min_response_time_ms?: number;
    max_response_time_ms?: number;
    p50_response_time_ms?: number;
    p95_response_time_ms?: number;
    p99_response_time_ms?: number;
    success_rate_percent?: number;
    check_count?: number;
};

export type MetricsResponse = {
    metrics: Array<{
        timestamp: Date;
        metric: Metric;
    }>;
    pagination: Pagination;
};

export type SummaryStatistics = {
    time_range?: string;
    total_agents?: number;
    active_agents?: number;
    inactive_agents?: number;
    total_targets?: number;
    reachable_targets?: number;
    unreachable_targets?: number;
    degraded_targets?: number;
    total_checks?: number;
    successful_checks?: number;
    failed_checks?: number;
    average_response_time_ms?: number;
    active_alerts?: number;
    by_agent?: Array<{
        agent_id?: UuiDv7;
        hostname?: string;
        status?: string;
        checks_performed?: number;
        success_rate_percent?: number;
    }>;
};

export type Alert = {
    id: string;
    rule_id: string;
    title?: string;
    description?: string;
    status: AlertStatus;
    severity: 'critical' | 'warning' | 'info';
    agent_id?: string;
    target?: string;
    metric_type?: string;
    threshold_value?: number;
    current_value?: number;
    created_at: Date;
    acknowledged_at?: Date | null;
    acknowledged_by?: string | null;
    resolved_at?: Date | null;
};

export type AlertRule = {
    readonly id?: string;
    name: string;
    description?: string;
    enabled?: boolean;
    condition: AlertCondition;
    severity: 'critical' | 'warning' | 'info';
    notifications: Array<NotificationChannel>;
    /**
     * Minimum time between repeat notifications
     */
    cooldown_seconds?: number;
};

export type AlertCondition = {
    metric: 'response_time_ms' | 'packet_loss_percent' | 'status' | 'uptime_percent';
    operator: 'greater_than' | 'less_than' | 'equals' | 'not_equals';
    threshold: number;
    /**
     * Condition must be true for this duration before alerting
     */
    duration_seconds?: number;
    aggregation?: 'avg' | 'min' | 'max' | 'sum' | 'count';
    filters?: {
        agent_ids?: Array<string>;
        targets?: Array<string>;
        metric_types?: Array<string>;
    };
};

export type NotificationChannel = {
    type: 'discord' | 'email' | 'webhook' | 'slack' | 'pagerduty' | 'teams';
    /**
     * Channel-specific configuration
     */
    configuration?: {
        [key: string]: unknown;
    };
};

export type TokenResponse = {
    /**
     * Server-managed opaque session token. Use as a Bearer token in the
     * Authorization header for all subsequent requests.
     * Format: st_live_<hex> (production) or st_test_<hex> (dev/test).
     *
     */
    opaque_token: string;
    /**
     * Hard expiry time (ISO 8601). The session will never be valid after
     * this timestamp regardless of activity. Use this to schedule a
     * proactive re-login in the client (e.g. at the midpoint).
     *
     */
    expires_at: Date;
};

export type UserInfo = {
    /**
     * Subject identifier (user ID)
     */
    sub: string;
    email?: string;
    email_verified?: boolean;
    name?: string;
    given_name?: string;
    family_name?: string;
    picture?: string;
    organization_id?: string;
    roles?: Array<string>;
    permissions?: Array<string>;
};

export type User = {
    id: string;
    email: string;
    name?: string;
    roles?: Array<'admin' | 'operator' | 'viewer'>;
    organization_id?: string;
    status?: UserStatus;
    created_at: Date;
    updated_at?: Date;
    last_login_at?: Date | null;
    /**
     * Which OAuth2 provider the user authenticated with
     */
    identity_provider?: string;
    /**
     * User ID from external identity provider
     */
    external_id?: string;
};

export type CreateUserRequest = {
    email: string;
    name?: string;
    roles: Array<'admin' | 'operator' | 'viewer'>;
    /**
     * Required for super admins creating users in other orgs
     */
    organization_id?: string;
};

export type UpdateUserRequest = {
    name?: string;
    status?: UpdateUserStatus;
    roles?: Array<'admin' | 'operator' | 'viewer'>;
};

export type Organization = {
    id: string;
    name: string;
    slug?: string;
    status?: OrganizationStatus;
    plan?: 'free' | 'professional' | 'enterprise';
    settings?: {
        max_agents?: number;
        retention_days?: number;
        features?: Array<string>;
    };
    created_at: Date;
    updated_at?: Date;
};

export type CreateOrganizationRequest = {
    name: string;
    slug?: string;
    plan?: 'free' | 'professional' | 'enterprise';
};

export type SystemStatus = {
    status: SystemHealthStatus;
    timestamp: Date;
    version?: string;
    uptime_seconds?: number;
    components?: ComponentsStatus;
};

export type ComponentsStatus = {
    [key: string]: ComponentStatus;
};

export type ComponentStatus = {
    status: ComponentHealthStatus;
    message?: string;
    response_time_ms?: number;
};

/**
 * Health status of the agent
 */
export const AgentHealthStatus = { HEALTHY: 'healthy', DEGRADED: 'degraded' } as const;

/**
 * Health status of the agent
 */
export type AgentHealthStatus = typeof AgentHealthStatus[keyof typeof AgentHealthStatus];

/**
 * Status of a monitoring check
 */
export const MetricStatus = {
    REACHABLE: 'reachable',
    UNREACHABLE: 'unreachable',
    DEGRADED: 'degraded',
    UNKNOWN: 'unknown'
} as const;

/**
 * Status of a monitoring check
 */
export type MetricStatus = typeof MetricStatus[keyof typeof MetricStatus];

/**
 * Status of agent registration
 */
export const RegistrationStatus = { PENDING_CLAIM: 'pending_claim' } as const;

/**
 * Status of agent registration
 */
export type RegistrationStatus = typeof RegistrationStatus[keyof typeof RegistrationStatus];

/**
 * IP address family (IPv4 or IPv6)
 */
export const IpAddressFamily = { IPV4: 'ipv4', IPV6: 'ipv6' } as const;

/**
 * IP address family (IPv4 or IPv6)
 */
export type IpAddressFamily = typeof IpAddressFamily[keyof typeof IpAddressFamily];

/**
 * Pending claim status
 */
export const ClaimStatusPendingEnum = { PENDING_CLAIM: 'pending_claim' } as const;

/**
 * Pending claim status
 */
export type ClaimStatusPendingEnum = typeof ClaimStatusPendingEnum[keyof typeof ClaimStatusPendingEnum];

/**
 * Claimed status
 */
export const ClaimStatusClaimedEnum = { CLAIMED: 'claimed' } as const;

/**
 * Claimed status
 */
export type ClaimStatusClaimedEnum = typeof ClaimStatusClaimedEnum[keyof typeof ClaimStatusClaimedEnum];

/**
 * Status in claim response
 */
export const ClaimResponseStatus = { CLAIMED: 'claimed' } as const;

/**
 * Status in claim response
 */
export type ClaimResponseStatus = typeof ClaimResponseStatus[keyof typeof ClaimResponseStatus];

/**
 * Report acknowledgment status
 */
export const ReportAckStatus = { ACCEPTED: 'accepted', QUEUED: 'queued' } as const;

/**
 * Report acknowledgment status
 */
export type ReportAckStatus = typeof ReportAckStatus[keyof typeof ReportAckStatus];

/**
 * Metric status
 */
export const AggregatedMetricStatus = {
    REACHABLE: 'reachable',
    UNREACHABLE: 'unreachable',
    DEGRADED: 'degraded',
    UNKNOWN: 'unknown'
} as const;

/**
 * Metric status
 */
export type AggregatedMetricStatus = typeof AggregatedMetricStatus[keyof typeof AggregatedMetricStatus];

/**
 * Alert status
 */
export const AlertStatus = {
    ACTIVE: 'active',
    ACKNOWLEDGED: 'acknowledged',
    RESOLVED: 'resolved'
} as const;

/**
 * Alert status
 */
export type AlertStatus = typeof AlertStatus[keyof typeof AlertStatus];

/**
 * User account status
 */
export const UserStatus = {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    SUSPENDED: 'suspended'
} as const;

/**
 * User account status
 */
export type UserStatus = typeof UserStatus[keyof typeof UserStatus];

/**
 * Updated user status
 */
export const UpdateUserStatus = {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    SUSPENDED: 'suspended'
} as const;

/**
 * Updated user status
 */
export type UpdateUserStatus = typeof UpdateUserStatus[keyof typeof UpdateUserStatus];

/**
 * Organization status
 */
export const OrganizationStatus = {
    ACTIVE: 'active',
    SUSPENDED: 'suspended',
    TRIAL: 'trial'
} as const;

/**
 * Organization status
 */
export type OrganizationStatus = typeof OrganizationStatus[keyof typeof OrganizationStatus];

/**
 * System health status
 */
export const SystemHealthStatus = {
    HEALTHY: 'healthy',
    DEGRADED: 'degraded',
    UNHEALTHY: 'unhealthy'
} as const;

/**
 * System health status
 */
export type SystemHealthStatus = typeof SystemHealthStatus[keyof typeof SystemHealthStatus];

/**
 * Component health status
 */
export const ComponentHealthStatus = {
    HEALTHY: 'healthy',
    DEGRADED: 'degraded',
    UNHEALTHY: 'unhealthy'
} as const;

/**
 * Component health status
 */
export type ComponentHealthStatus = typeof ComponentHealthStatus[keyof typeof ComponentHealthStatus];

/**
 * UUID version 7 as per RFC 4122
 */
export type UuiDv7 = string;

export type Pagination = {
    page: number;
    page_size: number;
    total_items: number;
    total_pages: number;
    has_next?: boolean;
    has_previous?: boolean;
};

export type Error = {
    error: string;
    message: string;
    details?: Array<{
        field?: string;
        issue?: string;
    }>;
    request_id?: string;
    /**
     * Link to relevant documentation
     */
    documentation_url?: string;
};

export type AlertRuleWritable = {
    name: string;
    description?: string;
    enabled?: boolean;
    condition: AlertCondition;
    severity: 'critical' | 'warning' | 'info';
    notifications: Array<NotificationChannel>;
    /**
     * Minimum time between repeat notifications
     */
    cooldown_seconds?: number;
};

/**
 * Unique identifier for the agent
 */
export type AgentId = UuiDv7;

/**
 * Unique identifier for the alert
 */
export type AlertId = string;

/**
 * Unique identifier for the user
 */
export type UserId = string;

/**
 * Unique identifier for the organization
 */
export type OrganizationId = string;

export type RegisterAgentSelfData = {
    body: AgentSelfRegistration;
    path?: never;
    query?: never;
    url: '/agent/register';
};

export type RegisterAgentSelfErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type RegisterAgentSelfError = RegisterAgentSelfErrors[keyof RegisterAgentSelfErrors];

export type RegisterAgentSelfResponses = {
    /**
     * Agent registration request updated (idempotent)
     */
    200: AgentRegistrationResponse;
    /**
     * Agent registration request created
     */
    201: AgentRegistrationResponse;
};

export type RegisterAgentSelfResponse = RegisterAgentSelfResponses[keyof RegisterAgentSelfResponses];

export type GetAgentClaimStatusData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the agent
         */
        agentId: UuiDv7;
    };
    query?: never;
    url: '/agent/{agentId}/claim-status';
};

export type GetAgentClaimStatusErrors = {
    /**
     * Agent registration not found or expired
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type GetAgentClaimStatusError = GetAgentClaimStatusErrors[keyof GetAgentClaimStatusErrors];

export type GetAgentClaimStatusResponses = {
    /**
     * Claim status retrieved
     */
    200: ClaimStatusPending | ClaimStatusClaimed;
};

export type GetAgentClaimStatusResponse = GetAgentClaimStatusResponses[keyof GetAgentClaimStatusResponses];

export type PostClaimAgentData = {
    body: ClaimAgentRequest;
    path?: never;
    query?: never;
    url: '/agent/claim';
};

export type PostClaimAgentErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
    /**
     * Forbidden - Invalid claim token or expired
     */
    403: Error;
    /**
     * Agent registration not found
     */
    404: Error;
    /**
     * Agent already claimed
     */
    409: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type PostClaimAgentError = PostClaimAgentErrors[keyof PostClaimAgentErrors];

export type PostClaimAgentResponses = {
    /**
     * Agent claimed successfully
     */
    200: ClaimAgentResponse;
};

export type PostClaimAgentResponse = PostClaimAgentResponses[keyof PostClaimAgentResponses];

export type GetAgentConfigurationData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the agent
         */
        agentId: UuiDv7;
    };
    query?: never;
    url: '/agent/{agentId}/configuration';
};

export type GetAgentConfigurationErrors = {
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Not implemented
     */
    501: Error;
    /**
     * Internal server error
     */
    503: Error;
};

export type GetAgentConfigurationError = GetAgentConfigurationErrors[keyof GetAgentConfigurationErrors];

export type GetAgentConfigurationResponses = {
    /**
     * Configuration retrieved successfully
     */
    200: AgentConfig;
};

export type GetAgentConfigurationResponse = GetAgentConfigurationResponses[keyof GetAgentConfigurationResponses];

export type SendAgentHeartbeatData = {
    body: AgentHeartbeat;
    path: {
        /**
         * Unique identifier for the agent
         */
        agentId: UuiDv7;
    };
    query?: never;
    url: '/agent/{agentId}/heartbeat';
};

export type SendAgentHeartbeatErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
    /**
     * Internal server error
     */
    503: Error;
};

export type SendAgentHeartbeatError = SendAgentHeartbeatErrors[keyof SendAgentHeartbeatErrors];

export type SendAgentHeartbeatResponses = {
    /**
     * Heartbeat received
     */
    204: void;
};

export type SendAgentHeartbeatResponse = SendAgentHeartbeatResponses[keyof SendAgentHeartbeatResponses];

export type SubmitAgentResultsData = {
    body: BatchMonitoringResults;
    path: {
        /**
         * Unique identifier for the agent
         */
        agentId: UuiDv7;
    };
    query?: never;
    url: '/agent/{agentId}/results';
};

export type SubmitAgentResultsErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
    /**
     * Unprocessable entity - Semantically invalid request
     */
    422: Error;
    /**
     * Internal server error
     */
    503: Error;
};

export type SubmitAgentResultsError = SubmitAgentResultsErrors[keyof SubmitAgentResultsErrors];

export type SubmitAgentResultsResponses = {
    /**
     * Batch accepted for processing
     */
    202: ResultsBatchAcknowledgment;
};

export type SubmitAgentResultsResponse = SubmitAgentResultsResponses[keyof SubmitAgentResultsResponses];

export type ListAgentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of agents per page
         */
        page_size?: number;
    };
    url: '/agents';
};

export type ListAgentsErrors = {
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type ListAgentsError = ListAgentsErrors[keyof ListAgentsErrors];

export type ListAgentsResponses = {
    /**
     * Agent list retrieved successfully
     */
    200: AgentListResponse;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type GetResultReportData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Filter by specific agent(s)
         */
        agent_id?: Array<string>;
        /**
         * Filter by monitored target
         */
        target?: string;
        /**
         * Type of metric to retrieve
         */
        metric_type?: 'icmp_ping' | 'tcp_check' | 'http_check' | 'traceroute' | 'custom';
        /**
         * Start of time range (RFC3339 format)
         */
        start_time: Date;
        /**
         * End of time range (RFC3339 format)
         */
        end_time: Date;
        /**
         * Aggregation interval
         */
        aggregation?: '1m' | '5m' | '15m' | '1h' | '6h' | '1d';
        /**
         * Filter by status
         */
        status?: Array<'reachable' | 'unreachable' | 'degraded' | 'unknown'>;
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of results per page
         */
        page_size?: number;
        /**
         * Response format
         */
        format?: 'json' | 'csv';
    };
    url: '/result/report';
};

export type GetResultReportErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
    /**
     * Forbidden - Insufficient permissions
     */
    403: Error;
};

export type GetResultReportError = GetResultReportErrors[keyof GetResultReportErrors];

export type GetResultReportResponses = {
    /**
     * Report generated successfully
     */
    200: ResultReport;
};

export type GetResultReportResponse = GetResultReportResponses[keyof GetResultReportResponses];

export type GetMetricsData = {
    body?: never;
    path?: never;
    query: {
        agent_id: string;
        start_time: Date;
        end_time: Date;
        metric_type?: string;
    };
    url: '/result/metrics';
};

export type GetMetricsResponses = {
    /**
     * Metrics retrieved successfully
     */
    200: MetricsResponse;
};

export type GetMetricsResponse = GetMetricsResponses[keyof GetMetricsResponses];

export type GetSummaryData = {
    body?: never;
    path?: never;
    query?: {
        time_range?: '1h' | '24h' | '7d' | '30d';
    };
    url: '/result/summary';
};

export type GetSummaryResponses = {
    /**
     * Summary statistics retrieved
     */
    200: SummaryStatistics;
};

export type GetSummaryResponse = GetSummaryResponses[keyof GetSummaryResponses];

export type ListAlertsData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'active' | 'acknowledged' | 'resolved';
        severity?: 'critical' | 'warning' | 'info';
        page?: number;
        page_size?: number;
    };
    url: '/alerts';
};

export type ListAlertsResponses = {
    /**
     * Alerts retrieved successfully
     */
    200: {
        alerts?: Array<Alert>;
        pagination?: Pagination;
    };
};

export type ListAlertsResponse = ListAlertsResponses[keyof ListAlertsResponses];

export type CreateAlertData = {
    body: AlertRuleWritable;
    path?: never;
    query?: never;
    url: '/alerts';
};

export type CreateAlertErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Forbidden - Insufficient permissions
     */
    403: Error;
};

export type CreateAlertError = CreateAlertErrors[keyof CreateAlertErrors];

export type CreateAlertResponses = {
    /**
     * Alert rule created
     */
    201: AlertRule;
};

export type CreateAlertResponse = CreateAlertResponses[keyof CreateAlertResponses];

export type DeleteAlertData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the alert
         */
        alertId: string;
    };
    query?: never;
    url: '/alerts/{alertId}';
};

export type DeleteAlertErrors = {
    /**
     * Forbidden - Insufficient permissions
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeleteAlertError = DeleteAlertErrors[keyof DeleteAlertErrors];

export type DeleteAlertResponses = {
    /**
     * Alert rule deleted
     */
    204: void;
};

export type DeleteAlertResponse = DeleteAlertResponses[keyof DeleteAlertResponses];

export type GetAlertData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the alert
         */
        alertId: string;
    };
    query?: never;
    url: '/alerts/{alertId}';
};

export type GetAlertErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type GetAlertError = GetAlertErrors[keyof GetAlertErrors];

export type GetAlertResponses = {
    /**
     * Alert details retrieved
     */
    200: Alert;
};

export type GetAlertResponse = GetAlertResponses[keyof GetAlertResponses];

export type AcknowledgeAlertData = {
    body?: {
        /**
         * Optional note about the acknowledgment
         */
        note?: string;
    };
    path: {
        /**
         * Unique identifier for the alert
         */
        alertId: string;
    };
    query?: never;
    url: '/alerts/{alertId}/acknowledge';
};

export type AcknowledgeAlertErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type AcknowledgeAlertError = AcknowledgeAlertErrors[keyof AcknowledgeAlertErrors];

export type AcknowledgeAlertResponses = {
    /**
     * Alert acknowledged
     */
    200: Alert;
};

export type AcknowledgeAlertResponse = AcknowledgeAlertResponses[keyof AcknowledgeAlertResponses];

export type Oauth2AuthorizeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Identity provider name. Must match a provider configured on the server.
         * Built-in values: okta, auth0, azure, google, github.
         *
         */
        provider: string;
        /**
         * Space-separated list of requested scopes
         */
        scope: string;
        /**
         * CSRF protection token generated by the client
         */
        state: string;
        /**
         * PKCE code challenge (BASE64URL(SHA256(code_verifier)))
         */
        code_challenge: string;
        /**
         * PKCE code challenge method — must be S256
         */
        code_challenge_method: 'S256';
    };
    url: '/auth/oauth2/authorize';
};

export type Oauth2AuthorizeErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
};

export type Oauth2AuthorizeError = Oauth2AuthorizeErrors[keyof Oauth2AuthorizeErrors];

export type Oauth2CallbackData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Authorization code issued by the identity provider
         */
        code?: string;
        /**
         * CSRF protection token (must match the original authorize request)
         */
        state?: string;
        /**
         * Error code if authorization failed at the IDP
         */
        error?: string;
        /**
         * Human-readable error description from the IDP
         */
        error_description?: string;
    };
    url: '/auth/oauth2/callback';
};

export type Oauth2TokenData = {
    body: {
        /**
         * OAuth2 grant type (only authorization_code is supported here)
         */
        grant_type: 'authorization_code';
        /**
         * Authorization code returned by the IDP callback
         */
        code: string;
        /**
         * Must exactly match the redirect_uri used in the authorization request
         */
        redirect_uri: string;
        /**
         * PKCE code verifier corresponding to the code_challenge sent at /authorize
         */
        code_verifier: string;
    };
    path?: never;
    query?: never;
    url: '/auth/oauth2/token';
};

export type Oauth2TokenErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
};

export type Oauth2TokenError = Oauth2TokenErrors[keyof Oauth2TokenErrors];

export type Oauth2TokenResponses = {
    /**
     * Session created; opaque token returned
     */
    200: TokenResponse;
};

export type Oauth2TokenResponse = Oauth2TokenResponses[keyof Oauth2TokenResponses];

export type Oauth2RevokeData = {
    body: {
        /**
         * The opaque session token to revoke (as returned by /auth/oauth2/token or /auth/refresh)
         */
        opaque_token: string;
    };
    path?: never;
    query?: never;
    url: '/auth/oauth2/revoke';
};

export type Oauth2RevokeErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
};

export type Oauth2RevokeError = Oauth2RevokeErrors[keyof Oauth2RevokeErrors];

export type Oauth2RevokeResponses = {
    /**
     * Session revoked successfully.
     */
    200: {
        /**
         * Present if IdP revocation was skipped (provider limitation)
         */
        warning?: string;
    };
};

export type Oauth2RevokeResponse = Oauth2RevokeResponses[keyof Oauth2RevokeResponses];

export type AuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthRefreshErrors = {
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
};

export type AuthRefreshError = AuthRefreshErrors[keyof AuthRefreshErrors];

export type AuthRefreshResponses = {
    /**
     * New session token issued
     */
    200: TokenResponse;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type GetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/userinfo';
};

export type GetUserInfoErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
};

export type GetUserInfoError = GetUserInfoErrors[keyof GetUserInfoErrors];

export type GetUserInfoResponses = {
    /**
     * User information retrieved
     */
    200: UserInfo;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type LogoutData = {
    body?: {
        /**
         * Optional URI to redirect to after IDP logout completes.
         * Forwarded to the IDP end-session endpoint as post_logout_redirect_uri.
         *
         */
        post_logout_redirect_uri?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Logout acknowledged (providers without end-session endpoint, e.g. GitHub).
     *
     */
    200: {
        message?: string;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        organization_id?: string;
        role?: 'admin' | 'operator' | 'viewer';
        page?: number;
        page_size?: number;
    };
    url: '/users';
};

export type ListUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        users?: Array<User>;
        pagination?: Pagination;
    };
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type PostCreateUserData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/users';
};

export type PostCreateUserErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Forbidden - Insufficient permissions
     */
    403: Error;
};

export type PostCreateUserError = PostCreateUserErrors[keyof PostCreateUserErrors];

export type PostCreateUserResponses = {
    /**
     * User created successfully
     */
    201: User;
};

export type PostCreateUserResponse = PostCreateUserResponses[keyof PostCreateUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the user
         */
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type DeleteUserErrors = {
    /**
     * Forbidden - Insufficient permissions
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * User deleted successfully
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the user
         */
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type GetUserErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * User details retrieved
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type PatchUserData = {
    body: UpdateUserRequest;
    path: {
        /**
         * Unique identifier for the user
         */
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type PatchUserErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Forbidden - Insufficient permissions
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type PatchUserError = PatchUserErrors[keyof PatchUserErrors];

export type PatchUserResponses = {
    /**
     * User updated successfully
     */
    200: User;
};

export type PatchUserResponse = PatchUserResponses[keyof PatchUserResponses];

export type UpdateUserRolesData = {
    body: {
        roles: Array<'admin' | 'operator' | 'viewer'>;
    };
    path: {
        /**
         * Unique identifier for the user
         */
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/roles';
};

export type UpdateUserRolesResponses = {
    /**
     * Roles updated successfully
     */
    200: User;
};

export type UpdateUserRolesResponse = UpdateUserRolesResponses[keyof UpdateUserRolesResponses];

export type ListOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type ListOrganizationsResponses = {
    /**
     * Organizations retrieved
     */
    200: {
        organizations?: Array<Organization>;
    };
};

export type ListOrganizationsResponse = ListOrganizationsResponses[keyof ListOrganizationsResponses];

export type PostCreateOrganizationData = {
    body: CreateOrganizationRequest;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type PostCreateOrganizationResponses = {
    /**
     * Organization created
     */
    201: Organization;
};

export type PostCreateOrganizationResponse = PostCreateOrganizationResponses[keyof PostCreateOrganizationResponses];

export type GetOrganizationData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the organization
         */
        organizationId: string;
    };
    query?: never;
    url: '/organizations/{organizationId}';
};

export type GetOrganizationResponses = {
    /**
     * Organization details retrieved
     */
    200: Organization;
};

export type GetOrganizationResponse = GetOrganizationResponses[keyof GetOrganizationResponses];

export type GetWebSocketTokenData = {
    body: {
        /**
         * List of topics to subscribe to
         */
        subscriptions: Array<'alerts' | 'metrics' | 'agent_status' | 'system_events'>;
        /**
         * Optional filters for subscriptions
         */
        filters?: {
            agent_ids?: Array<string>;
            alert_severity?: Array<'critical' | 'warning' | 'info'>;
        };
    };
    path?: never;
    query?: never;
    url: '/websocket/token';
};

export type GetWebSocketTokenErrors = {
    /**
     * Bad request - Invalid parameters
     */
    400: Error;
    /**
     * Unauthorized - Invalid or missing authentication
     */
    401: Error;
};

export type GetWebSocketTokenError = GetWebSocketTokenErrors[keyof GetWebSocketTokenErrors];

export type GetWebSocketTokenResponses = {
    /**
     * WebSocket token generated
     */
    200: {
        /**
         * Temporary token for WebSocket connection
         */
        token: string;
        /**
         * WebSocket endpoint URL
         */
        websocket_url: string;
        /**
         * Token expiration time
         */
        expires_at: Date;
        /**
         * Confirmed subscriptions
         */
        subscriptions?: Array<string>;
    };
};

export type GetWebSocketTokenResponse = GetWebSocketTokenResponses[keyof GetWebSocketTokenResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthCheckErrors = {
    /**
     * Server is unhealthy
     */
    503: SystemStatus;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
    /**
     * Server is healthy
     */
    200: SystemStatus;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type ReadinessCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz/ready';
};

export type ReadinessCheckErrors = {
    /**
     * Server is not ready
     */
    503: unknown;
};

export type ReadinessCheckResponses = {
    /**
     * Server is ready
     */
    200: unknown;
};

export type LivenessCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz/live';
};

export type LivenessCheckResponses = {
    /**
     * Server is alive
     */
    200: unknown;
};

export type PrometheusMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics';
};

export type PrometheusMetricsResponses = {
    /**
     * Metrics in Prometheus format
     */
    200: string;
};

export type PrometheusMetricsResponse = PrometheusMetricsResponses[keyof PrometheusMetricsResponses];
